local file = fs.open("out.txt", "w")

file.write("80"..string.char("0x80").."\n")
file.write("81"..string.char("0x81").."\n")
file.write("82"..string.char("0x82").."\n")
file.write("83"..string.char("0x83").."\n")
file.write("84"..string.char("0x84").."\n")
file.write("85"..string.char("0x85").."\n")
file.write("86"..string.char("0x86").."\n")
file.write("87"..string.char("0x87").."\n")
file.write("88"..string.char("0x88").."\n")
file.write("89"..string.char("0x89").."\n")
file.write("8a"..string.char("0x8a").."\n")
file.write("8b"..string.char("0x8b").."\n")
file.write("8c"..string.char("0x8c").."\n")
file.write("8d"..string.char("0x8d").."\n")
file.write("8e"..string.char("0x8e").."\n")
file.write("8f"..string.char("0x8f").."\n")
file.write("90"..string.char("0x90").."\n")
file.write("91"..string.char("0x91").."\n")
file.write("92"..string.char("0x92").."\n")
file.write("93"..string.char("0x93").."\n")
file.write("94"..string.char("0x94").."\n")
file.write("95"..string.char("0x95").."\n")
file.write("96"..string.char("0x96").."\n")
file.write("97"..string.char("0x97").."\n")
file.write("98"..string.char("0x98").."\n")
file.write("99"..string.char("0x99").."\n")
file.write("9a"..string.char("0x9a").."\n")
file.write("9b"..string.char("0x9b").."\n")
file.write("9c"..string.char("0x9c").."\n")
file.write("9d"..string.char("0x9d").."\n")
file.write("9e"..string.char("0x9e").."\n")
file.write("9f"..string.char("0x9f").."\n")

file.close()